### ISSUE TITLE
home bazaar (App Suite) crashes

### ISSUE THREAD

**Issue by pathus-hiddyn** [holium/realm-support#10]
Getting the below crash report every time I try to open the app suite on my home space. App suite for other spaces renders fine. Tried deleting the bazaar.json as well as cache and also tried totally uninstalling and reinstalling but issue persisted.

<img width="947" alt="Screen Shot 2022-12-15 at 6 03 14 PM" src="https://user-images.githubusercontent.com/69367087/208000646-45226785-6a49-4641-b354-c1bfc3426a14.png">

**Comment by drunkplato** [comment]
We are working on these. Should be fixed in next update.

**Comment by drunkplato** [comment]
Try running the following command and restarting Realm. This should fix the issue.

`:bazaar &bazaar-action [%rebuild-catalog ~]`

**Comment by pathus-hiddyn** [comment]
> 

This worked @drunkplato ! Thanks!
