### ISSUE TITLE
Some Apps not working in Realm

### ISSUE THREAD

**Issue by energeia777** [holium/realm-support#11]
Studio, Sphinx, and Groups 2 are stuck spinning in my Realm

everything else seems to be working well so far

**Comment by drunkplato** [comment]
Do these apps show as installed in Landscape?

**Comment by energeia777** [comment]
in grid, yes
<img width="1161" alt="Screen Shot 2022-12-19 at 2 39 00 PM" src="https://user-images.githubusercontent.com/101355447/208506802-070f2328-c7ac-4db4-8acc-df93116054a7.png">

**Comment by drunkplato** [comment]
You can run the following command in your webterm to fix this:

`:bazaar &bazaar-action [%rebuild-catalog ~]`

**Comment by drunkplato** [comment]
I think I know what is happening here and we are working on solving it. We use the desk name rather than the desk.docket-0 `base` value to build the app url.

**Comment by ajlamarc** [comment]
Fixed!
