### ISSUE TITLE
Window resizing when pulling out of full screen 

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#12]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/82244264/208524284-ba9f543a-f5b8-4de0-9bdf-0b6dce01648b.png">
Probably not a high priority issue, but if you come out of full screen mode and use a Realm window smaller than the full frame, the windows within realm fail to resize. I understand this is not generally the expected use case for Realm, but figured I would log it anyways.

**Comment by ajlamarc** [comment]
The behavior here still isn't perfect - but windows don't go way off-screen anymore, only slightly, so I am closing this.
