### ISSUE TITLE
Cursor disappears when in a Realm window

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#13]
I have been having a recurring issue where my cursor disappears entirely when in a Realm window. If I exit and reboot Realm it fixes the issue for a bit but never permanently. I am not sure the *exact* trigger for this, so will add to this issue as I am able to further pin down the instances in which this happens, but I think it has something to do with leaving and coming back to the Realm app.

**Comment by ajlamarc** [comment]
Shouldn't be happening anymore.
