### ISSUE TITLE
Cannot reorder tiles in the Realm app grid view

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#14]
Ideally I would be able to reorder my app tiles same as I can in Tlon's grid view. Not sure where that state is shared landscape side, but perhaps could just pull in the same state such that changes on one or the other are replicated across both UIs?

**Comment by drunkplato** [comment]
We are tracking this in our internal project board. Will update you when it is in a new build.

**Comment by ajlamarc** [comment]
> Ideally I would be able to reorder my app tiles same as I can in Tlon's grid view. Not sure where that state is shared landscape side, but perhaps could just pull in the same state such that changes on one or the other are replicated across both UIs?

Hey sarlev, we've added support for sorting app tiles!  Stay posted for the next release of Realm.
