### ISSUE TITLE
Relic browser doesn't work

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#15]
Upon opening the Relic browser it will try to show me a `neeva.com` 'show me a thing' page for approximately a second before blanking out to just a grey box. If I type another website in the URL bar, nothing happens.

**Expected Behavior** 
Open to some home screen and then be able to use the application as a basic functional browser.

**Comment by drunkplato** [comment]
We have an open issue making Relic work. Will keep you updated.

**Comment by drunkplato** [comment]
We will be pushing the fixes for Relic today. Will let you know when that hits the update server.

**Comment by drunkplato** [comment]
`v0.0.65` is deploying now and should be solve most of the Relic browser issues. Opening links in Relic browser is still outstanding in another issue.

**Comment by thelifeandtimes** [comment]
Yup, looks like it is working for me. To look a gift horse in the mouth: Does Relic allow extensions? would be awesome to be able to use adblockers (even have one natively) and password managers.

**Comment by drunkplato** [comment]
doesn't currently allow extensions. we have a roadmap for the browser, but is probably going to wait until we have multiplayer before we dive into it deeply. 

Add it to the issue list as a recommendation. Closing this one for now.
