### ISSUE TITLE
Clicking a web link is broken

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#16]
In groups, whether in a collection or a chat, if someone shares a link, clicking on the link does not open the content in a browser window.

**Ideal Expected action**
Clicking a link opens the page in the Relic browser; this issue may be related to [github.com/holium/realm-support/issue/15](https://github.com/holium/realm-support/issues/15)

**Acceptable stepping stone**
Clicking a link opens the page in the default browser of my base OS.

**Comment by drunkplato** [comment]
We have this working for clicking links in DMs, but not in an Urbit app. Will add this to our issue list.

**Comment by drunkplato** [comment]
Fixed.

https://twitter.com/holium_corp/status/1606380961473515521
