### ISSUE TITLE
application dock selection dialog appears off screen

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#17]
When right clicking an application in the bottom dock, it looks like there is some sort of selection menu that is supposed to pop up, but instead of indexing upwards, it pushes downwards and so you can't read any of the options. You can click the top one which appears to be a 'pinning' or 'keep in dock' option.
<img width="357" alt="image" src="https://user-images.githubusercontent.com/82244264/209202206-57b0ca13-f6db-45e0-9783-097c4822c25c.png">

**Expected Behavior**
Selection menu should index upwards, like on macOS:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/82244264/209202303-0a190a86-26cc-4dff-ad35-ec366d75b244.png">

**Comment by drunkplato** [comment]
Literally have a fix for this today. Pushing in an hour or so.

**Comment by thelifeandtimes** [comment]
rad.

**Comment by drunkplato** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/6413077/209304148-d9dea514-c314-4fe4-a444-e67c51bed17d.png">
