### ISSUE TITLE
Full Screen scroll bars

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#2]
When in full screen mode, if I move my cursor to the bottom or right sides, a set of scroll bars appear. Initially there was a 'jitter' that would occur but that seems to have gone away (or been fixed), but regardless these scroll bars aren't particularly useful for any purpose and pull the user out of the immersive experience. Would be nice to have them removed.

**Comment by thelifeandtimes** [comment]
Potentially related; if I mouse over the greyed out wallet icon, the scrollbars appear and disappear 10+ times/second (the jitter I noted above).

**Comment by drunkplato** [comment]
This should be resolved. Let me know if the wallet icon jitter is still happening. I don't see it on my end.

**Comment by thelifeandtimes** [comment]
Both are fixed for me. Thanks!
