### ISSUE TITLE
Quote reply color conflicts in custom themes. 

### ISSUE THREAD

**Issue by j-w-code** [holium/realm-support#20]
****ISSUE:****
When using quote reply functionality in groups the default color palette often conflicts with custom theme colors. This renders the quoted portion unreadable. Images below. 

<img width="1155" alt="Screenshot 2022-12-26 at 1 21 29 PM" src="https://user-images.githubusercontent.com/102254836/209578519-2f7c257a-137a-470b-9452-dfb8cd5a124c.png">

<img width="1142" alt="Screenshot 2022-12-26 at 1 22 09 PM" src="https://user-images.githubusercontent.com/102254836/209578542-4200a00a-a998-4015-bfc7-57d885b9462b.png">

**STANDARD BEHAVIOR**
The below image shows a lighter theme with quote reply visible. 

 
<img width="1147" alt="Screenshot 2022-12-26 at 1 24 44 PM" src="https://user-images.githubusercontent.com/102254836/209578605-06e50d73-56d0-46f4-92a7-a5f673a9ee60.png">

**Comment by drunkplato** [comment]
This should be resolved in the update from last night. Make sure you are on `v0.0.68`
