### ISSUE TITLE
Realm says incorrect password if the ship's access code changes

### ISSUE THREAD

**Issue by jmrphy** [holium/realm-support#26]
This is obviously not very pressing but just to be thorough I'm putting everything I encounter here...

After I changed my access code on my ship, Realm was telling me that my Realm login password was incorrect. I'm pretty sure the password I was entering was not incorrect. I'm guessing that when I changed my access code, which logs you out of all web sessions, Realm could no longer get me into my ship because it only had my old access code.

So the issue is that Realm will tell users 'incorrect password' when that's not the problem.

**Comment by drunkplato** [comment]
This is very interesting. Will add to internal issue board
