### ISSUE TITLE
Rendering issue when adding members to space

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/realm-support#3]
In creating a new space and doing the initial step of assigning roles to participants, if the list is longer than the initial box, the user list will outrun the frame.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/82244264/207498394-f00dcd7d-7481-4eaa-a51f-f7d4cb3e2594.png">

Expected behavior would be to have the scroll happen just within the interior frame.

**Comment by drunkplato** [comment]
This should now be resolved if you "Check for updates" and have `v0.0.61`

**Comment by thelifeandtimes** [comment]
Yup, both seem fixed for me. Thanks!

**Comment by drunkplato** [comment]
Can you post a screenshot of the two scrollbars? I am not seeing the same thing on my side.

**Comment by thelifeandtimes** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/82244264/208524056-4ec01a37-6a3e-4d5e-8af5-13f295d6a332.png">
the outside one doesn't scroll a whole lot, but it is there.

**Comment by drunkplato** [comment]
Ahh, I thought I removed that one... ill double check.

**Comment by ajlamarc** [comment]
The second scrollbar is gone now for me as well
