### ISSUE TITLE
changing the name of a Space doesn't work

### ISSUE THREAD

**Issue by jmrphy** [holium/realm-support#4]
I learned that Chronicle currently requires a Group and a Space to have the same name.

So I went to change the name of my space, and it doesn't seem to take.

![CleanShot 2022-12-14 at 14 11 10](https://user-images.githubusercontent.com/2775529/207704773-6a6bdff1-dbcb-4c26-b1c8-56784970d432.gif)

**Comment by drunkplato** [comment]
You can only change the display name. The actual path will not change once it is created. 

So you can't change the path once it is created.

**Comment by jmrphy** [comment]
Thanks for clarifying. It was only an issue because I learned after the fact that Chronicle requires Groups and Spaces to have the same name. So this closed.
